// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf C++ Version: 5.29.3

#include "order.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace matching {

inline constexpr Order_pb::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : price_{0},
        type_{static_cast< ::matching::OrderType >(0)},
        side_{static_cast< ::matching::OrderSide >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Order_pb::Order_pb(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Order_pbDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Order_pbDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Order_pbDefaultTypeInternal() {}
  union {
    Order_pb _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Order_pbDefaultTypeInternal _Order_pb_default_instance_;
}  // namespace matching
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_order_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_order_2eproto = nullptr;
const ::uint32_t
    TableStruct_order_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::matching::Order_pb, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::matching::Order_pb, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::matching::Order_pb, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::matching::Order_pb, _impl_.side_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::matching::Order_pb)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::matching::_Order_pb_default_instance_._instance,
};
const char descriptor_table_protodef_order_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013order.proto\022\010matching\"_\n\010Order_pb\022\r\n\005p"
    "rice\030\001 \001(\002\022!\n\004type\030\002 \001(\0162\023.matching.Orde"
    "rType\022!\n\004side\030\003 \001(\0162\023.matching.OrderSide"
    "*\"\n\tOrderType\022\n\n\006MARKET\020\000\022\t\n\005LIMIT\020\001*\036\n\t"
    "OrderSide\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_order_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_order_2eproto = {
    false,
    false,
    196,
    descriptor_table_protodef_order_2eproto,
    "order.proto",
    &descriptor_table_order_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_order_2eproto::offsets,
    file_level_enum_descriptors_order_2eproto,
    file_level_service_descriptors_order_2eproto,
};
namespace matching {
const ::google::protobuf::EnumDescriptor* OrderType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_order_2eproto);
  return file_level_enum_descriptors_order_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t OrderType_internal_data_[] = {
    131072u, 0u, };
bool OrderType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
const ::google::protobuf::EnumDescriptor* OrderSide_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_order_2eproto);
  return file_level_enum_descriptors_order_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t OrderSide_internal_data_[] = {
    131072u, 0u, };
bool OrderSide_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class Order_pb::_Internal {
 public:
};

Order_pb::Order_pb(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:matching.Order_pb)
}
Order_pb::Order_pb(
    ::google::protobuf::Arena* arena, const Order_pb& from)
    : Order_pb(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Order_pb::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Order_pb::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, price_),
           0,
           offsetof(Impl_, side_) -
               offsetof(Impl_, price_) +
               sizeof(Impl_::side_));
}
Order_pb::~Order_pb() {
  // @@protoc_insertion_point(destructor:matching.Order_pb)
  SharedDtor(*this);
}
inline void Order_pb::SharedDtor(MessageLite& self) {
  Order_pb& this_ = static_cast<Order_pb&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Order_pb::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Order_pb(arena);
}
constexpr auto Order_pb::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Order_pb),
                                            alignof(Order_pb));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Order_pb::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Order_pb_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Order_pb::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Order_pb>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Order_pb::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Order_pb>(), &Order_pb::ByteSizeLong,
            &Order_pb::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Order_pb, _impl_._cached_size_),
        false,
    },
    &Order_pb::kDescriptorMethods,
    &descriptor_table_order_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Order_pb::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Order_pb::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::matching::Order_pb>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float price = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.price_)}},
    // .matching.OrderType type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Order_pb, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.type_)}},
    // .matching.OrderSide side = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Order_pb, _impl_.side_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.side_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float price = 1;
    {PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // .matching.OrderType type = 2;
    {PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .matching.OrderSide side = 3;
    {PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.side_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Order_pb::Clear() {
// @@protoc_insertion_point(message_clear_start:matching.Order_pb)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.price_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.side_) -
      reinterpret_cast<char*>(&_impl_.price_)) + sizeof(_impl_.side_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Order_pb::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Order_pb& this_ = static_cast<const Order_pb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Order_pb::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Order_pb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:matching.Order_pb)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float price = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_price()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_price(), target);
          }

          // .matching.OrderType type = 2;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_type(), target);
          }

          // .matching.OrderSide side = 3;
          if (this_._internal_side() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_side(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:matching.Order_pb)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Order_pb::ByteSizeLong(const MessageLite& base) {
          const Order_pb& this_ = static_cast<const Order_pb&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Order_pb::ByteSizeLong() const {
          const Order_pb& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:matching.Order_pb)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float price = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_price()) != 0) {
              total_size += 5;
            }
            // .matching.OrderType type = 2;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // .matching.OrderSide side = 3;
            if (this_._internal_side() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_side());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Order_pb::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Order_pb*>(&to_msg);
  auto& from = static_cast<const Order_pb&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:matching.Order_pb)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_price()) != 0) {
    _this->_impl_.price_ = from._impl_.price_;
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_side() != 0) {
    _this->_impl_.side_ = from._impl_.side_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Order_pb::CopyFrom(const Order_pb& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:matching.Order_pb)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Order_pb::InternalSwap(Order_pb* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.side_)
      + sizeof(Order_pb::_impl_.side_)
      - PROTOBUF_FIELD_OFFSET(Order_pb, _impl_.price_)>(
          reinterpret_cast<char*>(&_impl_.price_),
          reinterpret_cast<char*>(&other->_impl_.price_));
}

::google::protobuf::Metadata Order_pb::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace matching
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_order_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
