// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf C++ Version: 5.29.3

#ifndef order_2eproto_2epb_2eh
#define order_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_order_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_order_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_order_2eproto;
namespace matching {
class Order_pb;
struct Order_pbDefaultTypeInternal;
extern Order_pbDefaultTypeInternal _Order_pb_default_instance_;
}  // namespace matching
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace matching {
enum OrderType : int {
  MARKET = 0,
  LIMIT = 1,
  OrderType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OrderType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OrderType_IsValid(int value);
extern const uint32_t OrderType_internal_data_[];
constexpr OrderType OrderType_MIN = static_cast<OrderType>(0);
constexpr OrderType OrderType_MAX = static_cast<OrderType>(1);
constexpr int OrderType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
OrderType_descriptor();
template <typename T>
const std::string& OrderType_Name(T value) {
  static_assert(std::is_same<T, OrderType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OrderType_Name().");
  return OrderType_Name(static_cast<OrderType>(value));
}
template <>
inline const std::string& OrderType_Name(OrderType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OrderType_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool OrderType_Parse(absl::string_view name, OrderType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OrderType>(
      OrderType_descriptor(), name, value);
}
enum OrderSide : int {
  BUY = 0,
  SELL = 1,
  OrderSide_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OrderSide_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OrderSide_IsValid(int value);
extern const uint32_t OrderSide_internal_data_[];
constexpr OrderSide OrderSide_MIN = static_cast<OrderSide>(0);
constexpr OrderSide OrderSide_MAX = static_cast<OrderSide>(1);
constexpr int OrderSide_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor*
OrderSide_descriptor();
template <typename T>
const std::string& OrderSide_Name(T value) {
  static_assert(std::is_same<T, OrderSide>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OrderSide_Name().");
  return OrderSide_Name(static_cast<OrderSide>(value));
}
template <>
inline const std::string& OrderSide_Name(OrderSide value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OrderSide_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool OrderSide_Parse(absl::string_view name, OrderSide* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OrderSide>(
      OrderSide_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class Order_pb final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:matching.Order_pb) */ {
 public:
  inline Order_pb() : Order_pb(nullptr) {}
  ~Order_pb() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Order_pb* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Order_pb));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Order_pb(
      ::google::protobuf::internal::ConstantInitialized);

  inline Order_pb(const Order_pb& from) : Order_pb(nullptr, from) {}
  inline Order_pb(Order_pb&& from) noexcept
      : Order_pb(nullptr, std::move(from)) {}
  inline Order_pb& operator=(const Order_pb& from) {
    CopyFrom(from);
    return *this;
  }
  inline Order_pb& operator=(Order_pb&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Order_pb& default_instance() {
    return *internal_default_instance();
  }
  static inline const Order_pb* internal_default_instance() {
    return reinterpret_cast<const Order_pb*>(
        &_Order_pb_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Order_pb& a, Order_pb& b) { a.Swap(&b); }
  inline void Swap(Order_pb* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Order_pb* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Order_pb* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Order_pb>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Order_pb& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Order_pb& from) { Order_pb::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Order_pb* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "matching.Order_pb"; }

 protected:
  explicit Order_pb(::google::protobuf::Arena* arena);
  Order_pb(::google::protobuf::Arena* arena, const Order_pb& from);
  Order_pb(::google::protobuf::Arena* arena, Order_pb&& from) noexcept
      : Order_pb(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPriceFieldNumber = 1,
    kTypeFieldNumber = 2,
    kSideFieldNumber = 3,
  };
  // float price = 1;
  void clear_price() ;
  float price() const;
  void set_price(float value);

  private:
  float _internal_price() const;
  void _internal_set_price(float value);

  public:
  // .matching.OrderType type = 2;
  void clear_type() ;
  ::matching::OrderType type() const;
  void set_type(::matching::OrderType value);

  private:
  ::matching::OrderType _internal_type() const;
  void _internal_set_type(::matching::OrderType value);

  public:
  // .matching.OrderSide side = 3;
  void clear_side() ;
  ::matching::OrderSide side() const;
  void set_side(::matching::OrderSide value);

  private:
  ::matching::OrderSide _internal_side() const;
  void _internal_set_side(::matching::OrderSide value);

  public:
  // @@protoc_insertion_point(class_scope:matching.Order_pb)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Order_pb& from_msg);
    float price_;
    int type_;
    int side_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_order_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Order_pb

// float price = 1;
inline void Order_pb::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
}
inline float Order_pb::price() const {
  // @@protoc_insertion_point(field_get:matching.Order_pb.price)
  return _internal_price();
}
inline void Order_pb::set_price(float value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:matching.Order_pb.price)
}
inline float Order_pb::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void Order_pb::_internal_set_price(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// .matching.OrderType type = 2;
inline void Order_pb::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::matching::OrderType Order_pb::type() const {
  // @@protoc_insertion_point(field_get:matching.Order_pb.type)
  return _internal_type();
}
inline void Order_pb::set_type(::matching::OrderType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:matching.Order_pb.type)
}
inline ::matching::OrderType Order_pb::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::matching::OrderType>(_impl_.type_);
}
inline void Order_pb::_internal_set_type(::matching::OrderType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// .matching.OrderSide side = 3;
inline void Order_pb::clear_side() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = 0;
}
inline ::matching::OrderSide Order_pb::side() const {
  // @@protoc_insertion_point(field_get:matching.Order_pb.side)
  return _internal_side();
}
inline void Order_pb::set_side(::matching::OrderSide value) {
  _internal_set_side(value);
  // @@protoc_insertion_point(field_set:matching.Order_pb.side)
}
inline ::matching::OrderSide Order_pb::_internal_side() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::matching::OrderSide>(_impl_.side_);
}
inline void Order_pb::_internal_set_side(::matching::OrderSide value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace matching


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::matching::OrderType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::matching::OrderType>() {
  return ::matching::OrderType_descriptor();
}
template <>
struct is_proto_enum<::matching::OrderSide> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::matching::OrderSide>() {
  return ::matching::OrderSide_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // order_2eproto_2epb_2eh
